// Action Types

//Authentication - login, signup

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const FORM_RESET = 'FORM_RESET';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CONFIRM_PASSWORD_CHANGED = 'CONFIRM_PASSWORD_CHANGED';
export const NEW_PASSWORD_CHANGED = 'NEW_PASSWORD_CHANGED';
export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED';
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_NEW_PASSWORD_REQUESTED = 'SET_NEW_PASSWORD_REQUESTED';
export const VERIFY_PASSWORD_CODE = 'VERIFY_PASSWORD_CODE';
export const PASSWORD_CODE_VERIFIED = 'PASSWORD_CODE_VERIFIED';
export const PASSWORD_CODE_INVALID = 'PASSWORD_CODE_INVALID';
export const EMAIL_LINK_SENT = 'EMAIL_LINK_SENT';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const LOADING = 'LOADING';


// POSTS


// Create Post
export const TITLE_CHANGED = 'TITLE_CHANGED';
export const TITLE_UPDATED = 'TITLE_UPDATED';
export const DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED';
export const DESCRIPTION_UPDATED = 'DESCRIPTION_UPDATED';
export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_FAIL = 'ADD_NOTE_FAIL';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_FAIL = 'UPDATE_NOTE_FAIL';
export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_IN_PROGRESS = 'EDIT_IN_PROGRESS';
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
export const CANCEL_EDIT = 'CANCEL_EDIT';
export const DELETE_NOTE = 'DELETE_NOTE';
export const NOTE_SELECTED = 'NOTE_SELECTED';

// Fetch Post
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

// Fetch Post Details
export const GET_POST_DETAILS = 'GET_POST_DETAILS';
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS';




// Modal
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';


// TODOS

export const FETCH_TODOS = 'FETCH_TODOS';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const TODO_TITLE_CHANGED = 'TODO_TITLE_CHANGED';
export const TODO_TASK_TITLE_CHANGED = 'TODO_TASK_TITLE_CHANGED';
export const ADD_TODO_TITLE = 'ADD_TODO_TITLE';
export const ADD_TODO_TITLE_SUCCESS = 'ADD_TODO_TITLE_SUCCESS';
export const ADD_TODO_TASK = 'ADD_TODO_TASK';
export const ADD_TODO_TASK_SUCCESS = 'ADD_TODO_TASK_SUCCESS';
export const COMPLETE_TODO_TASK = 'COMPLETE_TODO_TASK';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO_TASK = 'EDIT_TODO_TASK';
export const CLEAR_DATA = 'CLEAR_DATA';
export const TODO_FORM_RESET = 'TODO_FORM_RESET';


